Default: &defaults
  database: var2.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: var2_test.sqlite3
  <<: *defaults

Staging:
  database: var2_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: var2_production.sqlite3
  poolsize: 100
  <<: *defaults
